# Generated by Django 5.0.3 on 2024-04-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_datatype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_type', models.BooleanField(verbose_name='二元类型')),
                ('value_type', models.FloatField(verbose_name='数值类型')),
                ('diff_typr', models.FloatField(verbose_name='微分类型')),
                ('inte_type', models.FloatField(verbose_name='积分类型')),
            ],
            options={
                'db_table': 'device_datatype',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device_datatype')),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Binary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device_datatype')),
            ],
            options={
                'db_table': 'Binary',
            },
        ),
        migrations.CreateModel(
            name='Differential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('differential', models.FloatField(verbose_name='微分数值')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device_datatype')),
            ],
            options={
                'db_table': 'differential',
            },
        ),
        migrations.CreateModel(
            name='Integral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral', models.FloatField(verbose_name='积分数值')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device_datatype')),
            ],
            options={
                'db_table': 'integral',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='数值')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device_datatype')),
            ],
            options={
                'db_table': 'value',
            },
        ),
    ]
