name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: upload to server
      env:
        REMOTE_SSH_PRIV: ${{ secrets.REMOTE_SSH_PRIV }}
        IP_ADDR: ${{ secrets.IP_ADDR }}
      run: |
        echo "$REMOTE_SSH_PRIV" > ~/priv.key
        chmod 600 ~/priv.key
        scp -o StrictHostKeyChecking=no -i ~/priv.key -r ./* ubuntu@"$IP_ADDR":/www/server
        ssh -o StrictHostKeyChecking=no -f -n -i ~/priv.key ubuntu@"$IP_ADDR" "sudo systemctl restart backend;exit"
      

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
